import {notFound} from 'next/navigation';
import {marketServices} from '@/lib/market-services.mjs';
import {ButtonLink,Eyebrow,TextLink} from '@/components/site/UI';
import {pageMetadata} from '@/lib/site';
import {StockImage} from '@/components/site/StockImage';
import {Breadcrumbs,ServiceLd} from '@/components/site/StructuredData';
export const dynamicParams=false;
export function generateStaticParams(){return marketServices.map(service=>({slug:service.slug}));}
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props){const {slug}=await params;const service=marketServices.find(item=>item.slug===slug);return service?pageMetadata(`${service.title} · Creative Market`,service.summary,`/creative-market/${slug}`):{title:'Service not found'};}
export default async function MarketService({params}:Props){const {slug}=await params;const service=marketServices.find(item=>item.slug===slug);if(!service)notFound();return <><ServiceLd name={service.title} description={service.summary} path={`/creative-market/${service.slug}/`}/><Breadcrumbs items={[['Creative Market','/creative-market'],[service.title,`/creative-market/${service.slug}`]]}/><section className="container market-detail"><TextLink href="/creative-market#explore-services">All creative services</TextLink><Eyebrow>Creative Market · {service.group}</Eyebrow><h1>{service.title}</h1><p className="lead">{service.summary}</p><div className="actions"><ButtonLink href={`/creative-market/request?service=${encodeURIComponent(service.title)}`}>Request a match</ButtonLink><TextLink href="/creative-market/join">Work in this discipline?</TextLink></div><figure className="market-detail-photo" data-theme="dark"><StockImage name={service.image} sizes="(max-width:1279px) 92vw, 1200px" priority/></figure><div className="market-detail-grid"><section><h2>What your project could include</h2><ul>{service.deliverables.map(item=><li key={item}>{item}</li>)}</ul></section><section><h2>What helps us understand the brief</h2><ul>{service.brief.map(item=><li key={item}>{item}</li>)}</ul></section></div><p className="market-detail-note">These are starting points for a brief. The final scope, deliverables, usage rights, timeline and cost are agreed before work begins. A match depends on the project and creator availability.</p></section><section className="section surface-secondary"><div className="container editorial-split"><h2>Thinking beyond a single discipline?</h2><div><p className="lead">{service.adlab}</p><TextLink href="/adlab">Explore Pamsika AdLab</TextLink></div></div></section></>}
