import {Logo} from '@/components/brand/Logo';
import {ButtonLink,Eyebrow,SectionHeading,TextLink} from '@/components/site/UI';
import {ServiceCatalogue} from '@/components/market/ServiceCatalogue';
import {pageMetadata} from '@/lib/site';
import {StockImage} from '@/components/site/StockImage';
import {MarketHero} from '@/components/market/MarketHero';
export const metadata=pageMetadata('Creative Market','Explore creative services, request a match for your project, or apply to join Pamsika Creative Market as a creator.','/creative-market');
export default function CreativeMarket(){return <>
<MarketHero/>
<section className="section surface-secondary" id="explore-services"><div className="container"><SectionHeading eyebrow="Explore the disciplines" title="What does your idea need?" description="Start with a specific skill or combine disciplines around your project."/><ServiceCatalogue/></div></section>
<section className="section container"><SectionHeading eyebrow="A considered connection" title="Your brief. A shared starting point."/><div className="process-grid market-process">{[['01','Tell us what you need','Choose a discipline and share your goals, timing and budget. A focused brief helps us understand the work.'],['02','Explore a match','Pamsika reviews your request and explores suitable creative support. An introduction depends on fit and availability.'],['03','Agree the work','Confirm the scope, deliverables, usage, timeline and cost with the people involved before a project begins.']].map(([n,title,text])=><article key={n}><span className="process-number">{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="section market-creator-section" data-theme="dark"><StockImage name="portrait-artist" className="section-photo" sizes="100vw" position="center 45%"/><div className="container editorial-split"><div><Eyebrow>For independent creatives and studios</Eyebrow><h2>Your craft deserves its next opportunity.</h2></div><div><p className="lead">Show us what you do, where you work and the projects you want to take on. Apply to be considered for the Creative Market network.</p><p>We’re gathering creator applications. Profiles and work will be published only after review and permission.</p><ButtonLink href="/creative-market/join">Apply as a creator</ButtonLink></div></div></section>
<section className="section container market-adlab"><div><Eyebrow>Two ways to move forward</Eyebrow><h2>A creative skill.<br/>Or the whole campaign.</h2><p className="lead">Creative Market starts with the craft your project needs. AdLab brings strategy, creative direction and production together around a campaign.</p></div><div className="market-adlab-panel"><Logo kind="adlab" dark width={220}/><h3>Build the bigger idea.</h3><p>For a campaign shaped around your business from the first insight to the final frame.</p><ButtonLink href="/adlab" variant="accent">Explore AdLab</ButtonLink></div></section>
</>}
