import {ButtonLink,CTA,Eyebrow,SectionHeading,TextLink} from '@/components/site/UI';
import {Logo} from '@/components/brand/Logo';
import {ArrowUpRight,Clapperboard,Lightbulb,TrendingUp} from 'lucide-react';
import {marketServices} from '@/lib/market-services.mjs';
import {pageMetadata} from '@/lib/site';
export const metadata=pageMetadata('Ideas that move business.','Grow with Pamsika AdLab campaigns and Creative Market services: creativity, AI-powered production and African cultural intelligence.','/');
export default function Home(){return <>
<section className="home-hero container"><div className="hero-copy"><Eyebrow>African ambition. Amplified.</Eyebrow><h1>Ideas that<br/>move <span>business.</span></h1><p className="lead">Your ambition deserves a bigger stage. We bring creativity, technology and local intelligence together to help your business make its next move.</p><div className="actions"><ButtonLink href="/start-a-campaign">Start a campaign</ButtonLink><TextLink href="#our-offerings">Explore our offerings</TextLink></div><div className="hero-note"><span className="short-rule"/><p>AI-powered. Human-led.<br/>Built for African business.</p></div></div><figure className="hero-image"><img src="/media/founder-1280.webp" srcSet="/media/founder-640.webp 640w, /media/founder-1280.webp 1280w, /media/founder-1672.webp 1672w" sizes="(max-width:767px) 100vw, 50vw" width="1672" height="941" alt="Illustrative campaign portrait of a fashion entrepreneur in her studio" fetchPriority="high"/><div className="hero-image-copy"><span className="eyebrow">The ambition behind the business</span><p>Built here.<br/>Ready for more.</p></div><figcaption>AdLab creative direction · Illustrative concept</figcaption></figure></section>
<section className="container faq-first-visit" aria-label="New to Pamsika"><p><strong>First time here?</strong> Understand the platform and find your next step.</p><TextLink href="/faq?view=guide">Help me choose</TextLink></section>
<div className="capability-strip"><div className="container"><span>Business meets possibility.</span><span>Strategy</span><span>Creativity</span><span>Technology</span><span>Culture</span></div></div>
<section id="meet-adlab" className="section dark-section" data-theme="dark"><div className="container"><SectionHeading eyebrow="Meet our flagship" title="Big ideas. Made to move." description="Pamsika AdLab turns business ambition into advertising people feel, remember and act on." action={<TextLink href="/adlab">Explore AdLab</TextLink>}/><div className="adlab-feature"><figure className="feature-image"><img src="/media/citrus-1280.webp" width="1672" height="941" alt="Illustrative product concept with a chilled citrus drink in dramatic studio light" loading="lazy"/><figcaption>Product campaign · Illustrative concept</figcaption></figure><div className="feature-copy"><Logo kind="adlab" dark width={264}/><h3>Malawian stories.<br/>World-class commercials.</h3><p>From the first insight to the final frame. Original concepts, AI-assisted commercial production and locally relevant campaigns, made around what your business needs.</p><div className="inline-tags"><span>Brand films</span><span>Product campaigns</span><span>Social content</span></div><ButtonLink href="/work" variant="accent">Explore the ideas</ButtonLink></div></div></div></section>
<section className="section container market-home-card" id="meet-creative-market"><div><Eyebrow>Meet Creative Market</Eyebrow><h2>The craft behind your next move.</h2><p className="lead">Find a starting point for your project, from photography and design to writing, sound and motion. Share a brief to explore a creative match, or apply to join as a creator.</p><div className="actions"><ButtonLink href="/creative-market">Explore Creative Market</ButtonLink><TextLink href="/creative-market/join">For creators</TextLink></div></div><div className="market-home-links">{marketServices.map(service=><a href={`/creative-market/${service.slug}`} key={service.slug}>{service.title}<ArrowUpRight size={20} aria-hidden/></a>)}</div></section>
<section className="section container"><SectionHeading eyebrow="More than a good-looking ad" title="Built around your business." description="A clear idea, the right creative expression and a practical path to market."/><div className="service-grid">{[{Icon:Lightbulb,n:'01',title:'Find the idea',text:'Turn your business challenge into a focused creative direction. We start with your audience and the action you want them to take.'},{Icon:Clapperboard,n:'02',title:'Make it matter',text:'Bring the idea to life through film, design and content. Technology expands the possibilities. Human judgment gives it purpose.'},{Icon:TrendingUp,n:'03',title:'Move it forward',text:'Shape the campaign for the places your audience spends time, with formats and messaging that work together.'}].map(({Icon,n,title,text})=><article className="service-card" key={n}><div className="card-top"><Icon size={28} strokeWidth={1.75} aria-hidden/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="section-tail"><TextLink href="/services">Explore our services</TextLink></div></section>
<section className="section surface-secondary" id="our-offerings"><div className="container platform-row"><div><Eyebrow>One platform. Growing possibilities.</Eyebrow><h2>Start with the idea.<br/>Grow from there.</h2></div><div><p className="lead">Two ways to move your business forward: AdLab for a campaign from idea to execution, and Creative Market for the creative skills your project needs. Pamsika is the platform that brings them together.</p><div className="platform-list"><LinkRow title="Pamsika AdLab" state="Explore" href="/adlab"/><div><span>AI Business Studio</span><span className="quiet-label">Future offering</span></div><LinkRow title="Creative Market" state="Explore" href="/creative-market"/></div></div></div></section><CTA/>
</>}
function LinkRow({title,state,href}:{title:string;state:string;href:string}){return <a href={href}><span>{title}</span><span>{state}<ArrowUpRight size={18} aria-hidden/></span></a>}
