/** Published website guidance. Update this source when an offering or operating policy changes. */
export const faqs=[
 {id:'what-is-pamsika',topic:'Start here',question:'What is Pamsika, in plain language?',answer:'Pamsika helps African businesses turn their ideas into clearer communication and creative work. It brings together business thinking, creativity and technology. Start with AdLab for a campaign from idea to production, or Creative Market when you need a particular creative skill.',keywords:'explain business company platform purpose first new visitor does do',href:'/about',action:'Get to know Pamsika'},
 {id:'choose-an-offering',topic:'Start here',question:'Should I use AdLab or Creative Market?',answer:'Choose AdLab when you want a campaign shaped around a business goal, including strategy, creative direction and production. Choose Creative Market when you have a project and need a particular discipline, such as photography, design or writing. If you are unsure, describe your goal in a campaign brief so the right scope can be explored.',keywords:'difference compare choose which offering service right help decide',href:'/faq?view=guide',action:'Help me choose'},
 {id:'who-is-it-for',topic:'Start here',question:'Who can use Pamsika?',answer:'Pamsika is built around African business ambition. You might be introducing a product, developing your brand, reaching a new audience or looking for creative support. Independent creatives and studios can also apply to Creative Market. Describe your business stage and needs in your brief; the scope is discussed before any work is agreed.',keywords:'small businesses startup entrepreneur established organisation company beginner',href:'/services',action:'Explore business services'},
 {id:'where-we-work',topic:'Start here',question:'Can I enquire from outside Malawi?',answer:'You can share an enquiry and specify your country, audience, language and any shoot location. AdLab has a Malawian creative focus within Pamsika’s wider African business-growth purpose. Whether a project can be supported depends on its scope, location and available creative support; the website does not guarantee coverage in every market.',keywords:'africa country countries region location international remote malawi local',href:'/contact',action:'Discuss your market'},
 {id:'available-now',topic:'Start here',question:'Which Pamsika offerings are available now?',answer:'The website currently supports AdLab campaign enquiries and Creative Market project requests and creator applications. AI Business Studio is a future offering. The Creative Market catalogue shows disciplines you can request; it does not yet show a public roster of approved creators.',keywords:'live launch available current future studio products',href:'/creative-market',action:'Explore Creative Market'},
 {id:'adlab-services',topic:'AdLab & ideas',question:'What does AdLab help me create?',answer:'AdLab covers creative strategy, commercial production, social campaigns, and brand and campaign design. Depending on the agreed scope, a project may include concepts, scripts, storyboards, film, imagery, motion or channel-specific content. The proposal defines the actual deliverables; these are possibilities, not a fixed package.',keywords:'advert ads advertising videos commercials brand film social marketing campaign production',href:'/adlab',action:'Explore AdLab'},
 {id:'no-idea-yet',topic:'AdLab & ideas',question:'Can I start without a finished idea or brief?',answer:'Yes. Start with the business problem: what you offer, who you want to reach and what you want them to do. Include any timing or budget considerations. You do not need a finished script or storyboard to make an enquiry.',keywords:'begin start beginner no concept idea brief script need help',href:'/start-a-campaign',action:'Start with your business goal'},
 {id:'watch-work',topic:'AdLab & ideas',question:'What is Watch / Work, and are those real client campaigns?',answer:'Watch / Work is where you explore creative directions and campaign material. The current fashion-founder and citrus-product images are clearly labelled illustrative concepts. They are not presented as commissioned client projects or evidence of campaign results. Real campaign films and case studies will be identified when approved for publication.',keywords:'portfolio examples samples watch work video play images concepts clients results testimonials',href:'/work',action:'Explore the creative directions'},
 {id:'adapt-an-idea',topic:'AdLab & ideas',question:'What does “Adapt an idea” mean?',answer:'It means using a creative direction as a starting point for an original expression of your own brand. Tell us which idea inspired you and what you like about it, then explain your business and audience. It is not an instant download or a promise to copy someone else’s work.',keywords:'adapt adaptation inspiration reference recreate copy idea existing concept',href:'/adapt-an-idea',action:'Adapt an idea for your business'},
 {id:'share-reference',topic:'AdLab & ideas',question:'Can I bring my own reference or existing creative work?',answer:'Yes. Describe the reference or paste a link in your brief, along with what you want to achieve. Explain which assets belong to you and any known usage restrictions. Only share material you have permission to share; permissions and the intended use should be agreed before production.',keywords:'reference link existing brand materials assets own logo upload files',href:'/adapt-an-idea',action:'Share an inspiration link'},
 {id:'distribution-results',topic:'AdLab & ideas',question:'Does a campaign include ad placement or guaranteed sales?',answer:'Do not assume that media buying, advertising spend, ongoing channel management or performance reporting is included. Discuss those needs in your brief and have the proposal state what is covered. Pamsika does not promise a particular number of views, leads or sales through this website.',keywords:'facebook instagram tiktok ads placement media spend distribution results sales leads guarantee reach',href:'/start-a-campaign',action:'Describe your campaign goals'},
 {id:'market-how-it-works',topic:'Creative Market',question:'How does Creative Market work?',answer:'Creative Market currently uses a curated matching process. Explore the disciplines, submit your project brief, and Pamsika can review the need and explore suitable creative support. A match depends on fit and availability. Submitting a request does not instantly hire someone or guarantee that a creator is available.',keywords:'market marketplace how work match hire freelancer talent find book',href:'/creative-market/request',action:'Request a creative match'},
 {id:'market-disciplines',topic:'Creative Market',question:'What creative skills can I request?',answer:'The catalogue has six disciplines: film and video, design and branding, photography, writing and content, sound and voice, and animation and motion. You can select more than one in your brief. The service pages describe possible deliverables and the information that helps define a project.',keywords:'categories services skills photographer designer writer editor animator voiceover sound',href:'/creative-market#explore-services',action:'Browse the six disciplines'},
 {id:'market-listings',topic:'Creative Market',question:'Can I browse creator profiles, ratings and prices?',answer:'Not yet. The current catalogue is organised by creative discipline. Public creator profiles, reviews, ratings, fixed prices and live availability are not currently published. Creator applications are being collected for review; an application is not the same as an approved listing.',keywords:'profiles reviews ratings roster prices listed available verified talent creators browse',href:'/creative-market',action:'See the current catalogue'},
 {id:'digital-downloads',topic:'Creative Market',question:'Can I buy templates, graphics or instant downloads?',answer:'Creative Market is currently a service-matching offering. It is not a digital asset shop, and there is no instant-download checkout. If you need a template, graphic or other creative deliverable made for your business, describe it in a project request.',keywords:'buy purchase download templates graphics assets shop products store checkout',href:'/creative-market/request?service=Design%20and%20branding',action:'Request design support'},
 {id:'market-booking',topic:'Creative Market',question:'Am I booking a creator when I submit a request?',answer:'No. Your request records a brief for review. Before work starts, the people involved need to agree the scope, deliverables, timeline, usage and cost. There is no online booking or payment step in the current marketplace.',keywords:'booking reserve commitment hire contract request payment charge',href:'/creative-market/request',action:'Send a project request'},
 {id:'join-as-creator',topic:'For creators',question:'How do I join as a creator or studio?',answer:'Use the creator application form. Add your name, email, city and country, creative disciplines and a public HTTPS link to your portfolio or work profile. Tell us about your experience and the work you want to do. A studio or business name is optional.',keywords:'join signup sign register apply application creator studio freelancer portfolio become seller',href:'/creative-market/join',action:'Apply as a creator'},
 {id:'creator-approval',topic:'For creators',question:'Does applying make me an approved creator or guarantee work?',answer:'No. Submitting the form saves an application for review. It does not create a public profile, confirm acceptance or guarantee paid work. Any profile publication or introduction should be agreed with you. Keep the reference shown after submitting your application.',keywords:'accepted approved acceptance guarantee job jobs employment paid work application review',href:'/creative-market/join',action:'Read the application guidance'},
 {id:'creator-portfolio',topic:'For creators',question:'What portfolio link should I provide?',answer:'Provide a public HTTPS link to your website, portfolio or professional work profile. Choose work that shows your contribution and that you are allowed to share. The application accepts a link rather than a file upload. Do not include passwords or private client material.',keywords:'portfolio url https link work samples upload attach attachments files cv resume',href:'/creative-market/join',action:'Open the creator application'},
 {id:'creator-fees',topic:'For creators',question:'What are the creator fees, commissions and payment terms?',answer:'The website has not published a creator fee schedule, commission rate or payout policy. Submitting an application does not charge you or commit you to paid work. Before accepting an opportunity, clarify the commercial terms, responsibilities and how payment will work.',keywords:'creator commission commissions payout fees paid payments earning revenue seller',href:'/contact',action:'Ask about creator terms'},
 {id:'pricing',topic:'Costs & process',question:'How much does a project cost?',answer:'There is no fixed public price list. Cost depends on the agreed scope, deliverables and production needs. The budget choices in the enquiry form are planning guides, not prices or automatic quotes. A project proposal should confirm the cost before work begins.',keywords:'cost costs price pricing charge quote quotation estimate expensive affordable budget how much',href:'/start-a-campaign',action:'Discuss a campaign budget'},
 {id:'timing',topic:'Costs & process',question:'How long does a project take?',answer:'Timing depends on the scope, creative process, production requirements and availability. Include your preferred launch date or deadline in your brief. The form’s timing choices express your preference; they do not reserve a delivery slot. Agree the schedule before starting.',keywords:'time timing long deadline turnaround deliver delivery urgent days weeks duration',href:'/start-a-campaign',action:'Share your target timing'},
 {id:'what-to-prepare',topic:'Costs & process',question:'What should I prepare before sending a brief?',answer:'Include your business or project name, goal, audience, desired deliverables, timing and any budget considerations. Reference links and existing brand guidance can help. For a shoot, mention the location; for writing or voice, mention the language. An early outline is enough to begin the conversation.',keywords:'prepare information requirements documents brief details submit need',href:'/start-a-campaign',action:'Prepare your campaign brief'},
 {id:'pay-online',topic:'Costs & process',question:'Do I pay or commit to anything when I submit a form?',answer:'No payment is taken by these forms, and submitting an enquiry does not book work. There is no online checkout. Confirm the scope, price and payment arrangements before agreeing a project. Do not put card details or bank credentials into an enquiry.',keywords:'payment pay money deposit checkout card commitment commitment purchase form free',href:'/faq#pricing',action:'Read how pricing works'},
 {id:'rights-revisions',topic:'Costs & process',question:'What about ownership, revisions, licences and cancellation?',answer:'These are project terms to settle before work starts. Ask the proposal or agreement to state what is delivered, permitted usage, any third-party asset restrictions, revision rounds, payment milestones and cancellation arrangements. The website does not publish a universal rights transfer, unlimited-revision or refund policy.',keywords:'ownership copyright rights licence license revisions changes refunds refund cancel cancellation terms',href:'/contact',action:'Clarify your project terms'},
 {id:'ai-production',topic:'AI & technology',question:'How does Pamsika use AI?',answer:'Pamsika combines AI-assisted creative production with human thinking and direction. Technology can expand creative possibilities; people still shape the purpose, story and quality of the work. The tools and workflow used for your project depend on the agreed scope. Discuss any restrictions on AI-generated content in your brief.',keywords:'artificial intelligence ai generated human people production technology tools ethical',href:'/adlab',action:'Explore human-led production'},
 {id:'ai-tools',topic:'AI & technology',question:'Is this an AI chatbot or a self-service AI tool?',answer:'This FAQ is an interactive guide that searches published Pamsika answers and helps you choose a next step. It does not generate AI replies or access your submissions. The website currently accepts project enquiries and creator applications. AI Business Studio is a future offering, not a tool you can use here today.',keywords:'ai chatbot chat bot assistant self service studio tools generate automatic question answers',href:'/faq?view=guide',action:'Try the next-step guide'},
 {id:'faq-search-privacy',topic:'AI & technology',question:'Are my FAQ searches saved or sent to an AI service?',answer:'The FAQ search and next-step guide run in your browser. This feature does not save your search questions or send them to an AI service. Enquiry and application forms are separate: those details are submitted when you choose to send them.',keywords:'search privacy searches questions history sent save saved ai data tracking',href:'/faq#form-data',action:'Read about form submissions'},
 {id:'after-submitting',topic:'Using the site',question:'What happens after I submit a brief or application?',answer:'You can review and edit your details before sending. When the record is saved successfully, the page shows a reference number and a “Save a copy” button. Keep both for follow-up. Saving an enquiry or application does not confirm a booking, creator approval or a completed match.',keywords:'submit submitted submission after next confirmation enquiry application success reference followup',href:'/faq#confirmation-email',action:'About confirmation emails'},
 {id:'confirmation-email',topic:'Using the site',question:'Will I receive a confirmation email or an immediate reply?',answer:'Automatic email notifications are not connected in the current version. The on-screen success message and reference number are your confirmation that the record was saved. No response-time guarantee is published. Save a copy before leaving the page.',keywords:'email confirmation response reply support waiting immediate notification received inbox',href:'/contact',action:'Contact Pamsika with your reference'},
 {id:'submission-problem',topic:'Using the site',question:'What if a form fails or I lose my connection?',answer:'If saving fails, the form displays an error and keeps your entered details on that page so you can retry. A retry of the same unchanged submission is protected against duplicates. Avoid refreshing or closing the page before success, because an unsent draft is not saved for later. Only the success message confirms that a record was saved.',keywords:'error failed failure broken connection internet retry duplicate offline lost draft form problem',href:'/contact',action:'Open the contact form'},
 {id:'form-data',topic:'Using the site',question:'What information do the forms collect?',answer:'The forms store your contact details and the brief or application information you submit so the request can be handled. Creator applications include a portfolio link. Consent is requested before sending. Do not include passwords, payment details or confidential files. Public creator profiles are not created automatically from an application.',keywords:'data information privacy personal secure confidential passwords consent stored forms details',href:'/contact',action:'Ask about your submitted details'},
 {id:'site-map',topic:'Using the site',question:'Where should I go on the website?',answer:'Home explains the platform. Why Pamsika explains our purpose and how we work. AdLab covers complete campaigns. Creative Market helps you request specific creative skills or apply as a creator. Watch / Work shows creative directions. Services explains campaign support. Adapt an idea starts from a reference. Start a campaign collects a brief. About explains Pamsika, and Contact handles other enquiries.',keywords:'navigate navigation menu sitemap site map where pages find lost website go',href:'/faq?view=guide',action:'Find my next step'},
 {id:'account-needed',topic:'Using the site',question:'Do I need an account or an app?',answer:'There is no separate Pamsika customer account or app required by these enquiry forms. This review version of the website may be restricted to invited viewers by its hosting access settings. It does not currently include a customer dashboard for managing projects or checking application status.',keywords:'account login log sign in signup app download dashboard status portal access private',href:'/faq#after-submitting',action:'How to keep your submission reference'},
];
export const faqTopics=['Start here','AdLab & ideas','Creative Market','For creators','Costs & process','AI & technology','Using the site'];
export const guidePaths=[
 {id:'campaign',label:'I want to launch or grow a business',title:'Start with Pamsika AdLab.',text:'Bring the business goal. AdLab is the route for a campaign that joins strategy, creative direction and production.',steps:['Describe your business and audience','Share what you want the campaign to achieve','Include timing and budget preferences'],href:'/start-a-campaign',action:'Start a campaign',faq:'no-idea-yet'},
 {id:'skill',label:'I need a particular creative skill',title:'Explore Creative Market.',text:'Start with the discipline your project needs, then submit a brief to explore a suitable match.',steps:['Browse the six creative disciplines','Choose one or more skills for your brief','Discuss fit and scope before agreeing work'],href:'/creative-market',action:'Find creative support',faq:'market-how-it-works'},
 {id:'creator',label:'I am a creator or run a studio',title:'Apply to Creative Market.',text:'Share your craft and portfolio to be considered for the creative network. Applying does not create a public listing or guarantee work.',steps:['Choose your creative disciplines','Add your location and a public portfolio link','Submit your application for review'],href:'/creative-market/join',action:'Apply as a creator',faq:'join-as-creator'},
 {id:'idea',label:'I have seen an idea I like',title:'Make the idea your own.',text:'Use Adapt an idea to explain the direction you love and what makes your own business different.',steps:['Choose a concept or provide a reference link','Explain what inspires you about it','Describe your audience and desired outcome'],href:'/adapt-an-idea',action:'Adapt an idea',faq:'adapt-an-idea'},
 {id:'explore',label:'I want to see what the work could look like',title:'Visit Watch / Work.',text:'Explore the current creative directions. The existing stills are labelled illustrative concepts, so you can distinguish inspiration from commissioned client work.',steps:['Explore a creative direction','Read how the concept is presented','Use it as a starting point for your own brief'],href:'/work',action:'Explore the ideas',faq:'watch-work'},
 {id:'unsure',label:'I am still working out what I need',title:'Start with the business challenge.',text:'You do not need a perfect brief. Tell us what your business does and what you want to change, and the scope can be explored from there.',steps:['Name the challenge in a sentence','Describe who you want to reach','Share any timing or budget constraints'],href:'/start-a-campaign',action:'Share your starting point',faq:'choose-an-offering'},
];
const stopWords=new Set('a an the and or to of for in on with my your i me we us it is are do does can could would should will be have has how what where when why this that as at so about please'.split(' '));
const tokens=value=>(value.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(word=>!stopWords.has(word));
export function searchFaq(query='',topic='All topics'){
 const pool=faqs.filter(item=>topic==='All topics'||item.topic===topic);
 if(!query.trim())return pool;
 const words=[...new Set(tokens(query))];if(!words.length)return [];
 return pool.map((item,index)=>{const question=tokens(item.question),keywords=tokens(item.keywords),answer=tokens(item.answer);let matches=0,score=0;for(const word of words){const match=list=>list.some(value=>value===word||(word.length>3&&value.length>3&&(value.startsWith(word)||word.startsWith(value))));const weight=match(question)?5:match(keywords)?3:match(answer)?1:0;if(weight){matches++;score+=weight;}}return {item,index,score,matches};}).filter(item=>item.matches>=Math.max(1,Math.ceil(words.length*.5))).sort((a,b)=>b.score-a.score||a.index-b.index).map(result=>result.item);
}
