'use client';
import {useState} from 'react';
import {ArrowUpRight,Search,Clapperboard,PenTool,Camera,Type,AudioLines,MoveUpRight} from 'lucide-react';
import {filterMarketServices} from '@/lib/market-services.mjs';
import {SiteLink as Link} from '@/components/site/SiteLink';
import {StockImage} from '@/components/site/StockImage';
const icons=[Clapperboard,PenTool,Camera,Type,AudioLines,MoveUpRight];
export function ServiceCatalogue(){
 const [query,setQuery]=useState(''),[group,setGroup]=useState('All');
 const results=filterMarketServices(query,group);
 return <div className="market-catalogue"><div className="market-controls"><div className="market-search"><label htmlFor="service-search">Find a creative service</label><div><Search size={20} aria-hidden/><input id="service-search" type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try photography, scripts or motion" maxLength={100}/></div></div><div className="market-filters" role="group" aria-label="Filter creative services">{['All','Production','Design','Content'].map(value=><button type="button" key={value} aria-pressed={group===value} onClick={()=>setGroup(value)}>{value}</button>)}</div></div><p className="market-result-count" role="status">{results.length} {results.length===1?'discipline':'disciplines'} to explore</p><div className="market-grid">{results.map(service=>{const Icon=icons[['film-and-video','design-and-branding','photography','writing-and-content','sound-and-voice','animation-and-motion'].indexOf(service.slug)];return <article className="market-card" key={service.slug}><StockImage name={service.image} className="market-card-photo" sizes="(max-width:767px) 92vw, (max-width:1279px) 46vw, 30vw"/><div className="market-card-top"><Icon size={28} strokeWidth={1.5} aria-hidden/><span>{service.group}</span></div><h3><Link href={`/creative-market/${service.slug}`}>{service.title}<ArrowUpRight size={22} aria-hidden/></Link></h3><p>{service.summary}</p><ul>{service.deliverables.map(item=><li key={item}>{item}</li>)}</ul><Link className="text-link" href={`/creative-market/request?service=${encodeURIComponent(service.title)}`}>Request a match<ArrowUpRight size={18} aria-hidden/></Link></article>})}</div>{results.length===0&&<div className="market-empty"><h3>No disciplines match that search.</h3><p>Try a broader term, or share your brief and we can explore what you need.</p><button type="button" className="button button-secondary" onClick={()=>{setQuery('');setGroup('All')}}>Clear search and filters</button><Link className="text-link" href="/creative-market/request">Tell us what you need<ArrowUpRight size={18} aria-hidden/></Link></div>}</div>;
}
