import {notFound} from 'next/navigation';
import {campaigns} from '@/lib/campaigns';
import {pageMetadata,SITE_URL} from '@/lib/site';
import {Breadcrumbs,JsonLd} from '@/components/site/StructuredData';
import {CampaignMedia} from '@/components/campaigns/CampaignMedia';
import {ButtonLink,Eyebrow,TextLink} from '@/components/site/UI';
export const dynamicParams=false;
export function generateStaticParams(){return campaigns.map(c=>({slug:c.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=campaigns.find(x=>x.slug===slug);return c?pageMetadata(c.title,c.description,`/work/${slug}`):{};}
export default async function CampaignPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=campaigns.find(x=>x.slug===slug);if(!c)notFound();return <div className="dark-section" data-theme="dark"><JsonLd data={{'@context':'https://schema.org','@type':'CreativeWork',name:c.title,description:c.description,genre:c.category,image:`${SITE_URL}/media/${c.image}-1672.webp`,creator:{'@id':`${SITE_URL}/#organization`},creativeWorkStatus:'Concept'}}/><Breadcrumbs items={[['Work','/work'],[c.title,`/work/${c.slug}`]]}/><div className="container campaign-detail-head"><TextLink href="/work">All creative directions</TextLink><Eyebrow>{c.category} · Illustrative concept</Eyebrow><h1>{c.title}</h1><p className="lead">{c.description}</p></div><div className="container"><CampaignMedia campaign={c}/></div><section className="section container editorial-split"><div><Eyebrow>The thinking</Eyebrow><h2>One idea.<br/>Your own expression.</h2></div><div><p className="lead">{c.idea}</p><div className="inline-tags">{c.formats.map(x=><span key={x}>{x}</span>)}</div><p>This direction is a starting point. Your audience, product and brand would shape an original campaign, with creative scope agreed before production.</p><div className="actions"><ButtonLink href={`/adapt-an-idea?idea=${encodeURIComponent(c.title)}`} variant="accent">Adapt this idea</ButtonLink></div></div></section></div>}
