'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,ArrowLeft,Download} from 'lucide-react';
import {validateEnquiry} from '@/lib/enquiry-validation.mjs';
import {marketServiceNames} from '@/lib/market-services.mjs';
const campaignServiceOptions=['Creative strategy','Commercial production','Social campaigns','Brand and design'];
type Fields={name:string;email:string;business:string;message:string;idea:string;market:string;budget:string;timing:string;consent:boolean;services:string[];website:string;portfolio:string};
export function EnquiryForm({kind}:{kind:'campaign'|'adapt'|'contact'|'market'|'creator'}){
 const isCreator=kind==='creator',isMarket=kind==='market'||isCreator,hasBrief=kind!=='contact'&&!isCreator;
 const serviceOptions=isMarket?marketServiceNames:campaignServiceOptions;
 const [fields,setFields]=useState<Fields>({name:'',email:'',business:'',message:'',idea:'',market:'',budget:'Discuss with us',timing:'Flexible',consent:false,services:[],website:'',portfolio:''});
 const[errors,setErrors]=useState<Record<string,string>>({}),[validationAttempt,setValidationAttempt]=useState(0),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[reference,setReference]=useState('');
 const requestId=useRef(''),summary=useRef<HTMLDivElement>(null),reviewHeading=useRef<HTMLHeadingElement>(null),successHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{requestId.current=crypto.randomUUID();const params=new URLSearchParams(location.search);setFields(v=>({...v,idea:params.get('idea')||'',services:serviceOptions.includes(params.get('service')||'')?[params.get('service')!]:[]}));},[]);
 useEffect(()=>{if(validationAttempt>0)summary.current?.focus()},[validationAttempt]);
 useEffect(()=>{if(review)reviewHeading.current?.focus()},[review]);
 useEffect(()=>{if(reference)successHeading.current?.focus()},[reference]);
 function update(key:keyof Fields,value:string|boolean|string[]){setFields(v=>({...v,[key]:value}));setErrors(e=>{const next={...e};delete next[key];return next});setFailure('');}
 function validate(){const result=validateEnquiry({...fields,kind,requestId:requestId.current});if(!result.success){setErrors(result.errors as Record<string,string>);setValidationAttempt(n=>n+1);return false;}setErrors({});return true;}
 async function submit(){if(!validate())return;setBusy(true);setFailure('');try{const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,kind,requestId:requestId.current}),signal:AbortSignal.timeout(15000)});const result=await response.json() as {errors?:Record<string,string>;error?:string;reference?:string};if(!response.ok){if(result.errors){setErrors(result.errors);setReview(false);setValidationAttempt(n=>n+1);}throw new Error(result.error||'Your enquiry could not be saved. Please try again.');}if(!result.reference)throw new Error("No confirmation was returned. Please try again.");setReference(result.reference);}catch(error){setFailure(error instanceof Error&&error.name==='TimeoutError'?'The connection took too long. Please retry; your enquiry will not be duplicated.':error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}}
 function download(){const text=`Pamsika ${isCreator?'creator application':'enquiry'}\nReference: ${reference}\n\n${Object.entries(fields).filter(([k])=>!['website','consent'].includes(k)).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v}`).join('\n')}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`${reference}.txt`;a.click();URL.revokeObjectURL(url);}
 if(reference)return <section className="form-success"><span className="success-icon"><Check size={32} aria-hidden/></span><h2 ref={successHeading} tabIndex={-1}>{isCreator?'Your application is saved.':'Your enquiry is saved.'}</h2><p>Thank you, {fields.name}. Keep your reference for any follow-up about this enquiry.</p><p className="submission-reference">{reference}</p><p className="helper">{isCreator?'Your application is awaiting review. It does not create a public profile or guarantee work.':'Your details have been recorded securely. You have not booked or paid for any work.'}</p><button className="button button-secondary" onClick={download}><Download size={18} aria-hidden/>Save a copy</button></section>;
 const field=(name:'name'|'email'|'business'|'idea'|'market'|'portfolio',label:string,required=false,type='text')=><div className="form-field"><label htmlFor={name}>{label}{required&&<span aria-hidden> *</span>}</label><input id={name} name={name} type={type} value={fields[name]} onChange={e=>update(name,e.target.value)} required={required} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`${name}-error`:undefined} autoComplete={name==='name'?'name':name==='email'?'email':name==='business'?'organization':'off'} maxLength={name==='portfolio'?2000:name==='idea'?1000:name==='name'?120:['business','market'].includes(name)?180:254}/>{errors[name]&&<p className="field-error" id={`${name}-error`}>{errors[name]}</p>}</div>;
 return <form className="enquiry-form" noValidate onSubmit={e=>{e.preventDefault();if(review){void submit();}else if(validate())setReview(true)}}>
 <div className="form-step-label"><span className={!review?'current':''}>01 · Your {isCreator?'application':kind==='contact'?'message':'brief'}</span><span className={review?'current':''}>02 · Review & send</span></div>
 {Object.keys(errors).length>0&&<div className="error-summary" role="alert" ref={summary} tabIndex={-1}><strong>A few details need your attention.</strong><ul>{Object.entries(errors).map(([key,message])=><li key={key}><a href={`#${key}`}>{message}</a></li>)}</ul></div>}
 {failure&&<p className="error-summary" role="alert">{failure}</p>}
 {review?<div className="review-panel"><h2 ref={reviewHeading} tabIndex={-1}>Ready to send?</h2><p>Check your details before sending your enquiry.</p><dl>{[['Name',fields.name],['Email',fields.email],[isCreator?'Studio / business':'Business',fields.business],['Portfolio',fields.portfolio],['Idea',fields.idea],['Services',fields.services.join(', ')],[isCreator?'Location':'Audience / market',fields.market],['Budget',hasBrief?fields.budget:''],['Timing',hasBrief?fields.timing:''],['Your message',fields.message]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="helper">You agree that Pamsika may use these details to respond to your enquiry.</p><div className="form-actions"><button className="button button-secondary" type="button" disabled={busy} onClick={()=>setReview(false)}><ArrowLeft size={18} aria-hidden/>Edit details</button><button className="button button-primary" type="submit" disabled={busy} aria-busy={busy}>{busy?'Saving…':isCreator?'Send application':'Send enquiry'}{!busy&&<ArrowUpRight size={18} aria-hidden/>}</button></div></div>:<>
 <div className="form-heading"><h2>{isCreator?'Tell us about your craft.':kind==='market'?'Let’s understand your project.':kind==='contact'?'Let’s talk.':kind==='adapt'?'Make the idea your own.':'Tell us about your next move.'}</h2><p>Fields marked * are required.</p></div>
 <div className="form-grid">{field('name','Your name',true)}{field('email','Email address',true,'email')}{field('business',isCreator?'Studio / business name (optional)':'Business name',hasBrief)}{kind!=='contact'&&field('market',isCreator?'City and country':'Audience or market',isCreator)}</div>
 {isCreator&&<>{field('portfolio','Portfolio or work profile URL',true,'url')}<p className="helper">Use a public HTTPS link to work you are allowed to share. We won’t publish it without your permission.</p></>}
 {kind==='adapt'&&field('idea','Which idea inspired you?',true)}
 {kind!=='contact'&&<fieldset className="service-choice" id="services" tabIndex={-1} aria-describedby={errors.services?'services-error':undefined}><legend>{isCreator?'Your creative disciplines *':isMarket?'What kind of creative support do you need? *':'What can we help with?'}</legend><div>{serviceOptions.map(s=><label key={s}><input type="checkbox" checked={fields.services.includes(s)} onChange={e=>update('services',e.target.checked?[...fields.services,s]:fields.services.filter(x=>x!==s))}/><span>{s}</span></label>)}</div>{errors.services&&<p className="field-error" id="services-error">{errors.services}</p>}</fieldset>}
 <div className="form-field"><label htmlFor="message">{isCreator?'Tell us about your work and experience':kind==='contact'?'Your message':kind==='adapt'?'How could it work for your business?':'What would you like to achieve?'} <span aria-hidden>*</span></label><textarea id="message" name="message" value={fields.message} onChange={e=>update('message',e.target.value)} rows={5} required maxLength={5000} aria-invalid={!!errors.message} aria-describedby={`message-help${errors.message?' message-error':''}`}/><p id="message-help" className="helper">{isCreator?'Share your experience, preferred projects, languages and how you work.':kind==='contact'?'Tell us how we can help.':'Share your goal, audience and any details that would help shape the brief.'}</p>{errors.message&&<p id="message-error" className="field-error">{errors.message}</p>}</div>
 {hasBrief&&<div className="form-grid"><div className="form-field"><label htmlFor="budget">Indicative budget</label><select id="budget" value={fields.budget} onChange={e=>update('budget',e.target.value)}>{['Discuss with us','Under MWK 1 million','MWK 1–3 million','MWK 3–10 million','Above MWK 10 million'].map(x=><option key={x}>{x}</option>)}</select><p className="helper">For planning only. A proposal confirms the price.</p></div><div className="form-field"><label htmlFor="timing">When are you looking to launch?</label><select id="timing" value={fields.timing} onChange={e=>update('timing',e.target.value)}>{['Flexible','Within a month','In 1–3 months','More than 3 months away'].map(x=><option key={x}>{x}</option>)}</select></div></div>}
 <div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off" value={fields.website} onChange={e=>update('website',e.target.value)}/></div>
 <div className="consent"><label><input id="consent" type="checkbox" checked={fields.consent} onChange={e=>update('consent',e.target.checked)} required aria-invalid={!!errors.consent} aria-describedby="privacy-note"/><span>I agree that Pamsika may use my details to respond to this enquiry. *</span></label>{errors.consent&&<p className="field-error">{errors.consent}</p>}<p id="privacy-note" className="helper">Your name, contact details and brief are stored to handle this request. Please leave out passwords, payment details and confidential files.</p></div>
 <button className="button button-primary" type="submit">{isCreator?'Review application':'Review enquiry'}<ArrowUpRight size={20} aria-hidden/></button><p className="helper after-submit">No payment or commitment is required.</p>
 </>}
 </form>;
}
